import { Presentation } from '../types/slides';

export const DEFAULT_PRESENTATION: Presentation = {
  id: 'hmd-demo-presentation',
  title: 'Présentation HMD Slides',
  aspectRatio: '16:9',
  themeId: 'moderne',
  author: 'Équipe HMD Slides',
  version: '2.0.0',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  slides: [
    // Diapositive 1 : Titre & Introduction
    {
      id: 'slide-1',
      title: 'Titre & Introduction',
      layout: 'title',
      notes:
        'Bienvenue dans HMD Slides ! Préciser à l’audience que cette présentation a été entièrement conçue et peut être exportée en HTML 100% autonome sans aucun serveur.',
      transition: { type: 'fade', duration: 0.6 },
      background: {
        type: 'gradient',
        color: '#0f172a',
        gradient: {
          from: '#090d16',
          to: '#1e1b4b',
          direction: 'to-br',
        },
      },
      elements: [
        {
          id: 'el-bg-glow-1',
          type: 'shape',
          name: 'Lueur décorative 1',
          shapeType: 'ellipse',
          x: 60,
          y: -80,
          width: 380,
          height: 380,
          rotation: 0,
          opacity: 0.15,
          zIndex: 1,
          fillType: 'gradient',
          gradientStart: '#6366f1',
          gradientEnd: '#ec4899',
          strokeWidth: 0,
          animation: {
            type: 'fade-in',
            trigger: 'after-previous',
            duration: 0.8,
            delay: 0,
            order: 1,
          },
        },
        {
          id: 'el-bg-glow-2',
          type: 'shape',
          name: 'Lueur décorative 2',
          shapeType: 'ellipse',
          x: 680,
          y: 260,
          width: 420,
          height: 420,
          rotation: 0,
          opacity: 0.12,
          zIndex: 2,
          fillType: 'gradient',
          gradientStart: '#06b6d4',
          gradientEnd: '#3b82f6',
          strokeWidth: 0,
        },
        {
          id: 'el-tag-badge',
          type: 'shape',
          name: 'Plaque Badge',
          shapeType: 'rounded-rect',
          x: 100,
          y: 90,
          width: 250,
          height: 38,
          rotation: 0,
          opacity: 0.9,
          zIndex: 3,
          fillColor: 'rgba(99, 102, 241, 0.2)',
          strokeColor: '#6366f1',
          strokeWidth: 1.5,
          borderRadius: 19,
          animation: {
            type: 'fade-in',
            trigger: 'after-previous',
            duration: 0.5,
            delay: 0.1,
            order: 2,
          },
        },
        {
          id: 'el-tag-text',
          type: 'text',
          name: 'Texte Badge',
          content: '✨ SUITE DE PRÉSENTATION MODERNE',
          x: 110,
          y: 97,
          width: 230,
          height: 24,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          fontSize: 12,
          fontWeight: '700',
          fontFamily: 'Cabinet Grotesk, sans-serif',
          color: '#818cf8',
          textAlign: 'center',
          letterSpacing: 1,
        },
        {
          id: 'el-main-title',
          type: 'text',
          name: 'Titre Principal',
          content: 'Créez des Diaporamas\nFluides & Époustouflants',
          x: 100,
          y: 150,
          width: 780,
          height: 150,
          rotation: 0,
          opacity: 1,
          zIndex: 5,
          fontSize: 54,
          fontWeight: '800',
          fontFamily: 'Cabinet Grotesk, sans-serif',
          color: '#ffffff',
          textAlign: 'left',
          lineHeight: 1.15,
          shadow: true,
          shadowColor: 'rgba(0,0,0,0.5)',
          shadowBlur: 16,
          animation: {
            type: 'slide-up',
            trigger: 'after-previous',
            duration: 0.7,
            delay: 0.1,
            order: 3,
          },
        },
        {
          id: 'el-subtitle',
          type: 'text',
          name: 'Sous-titre',
          content:
            'L’alternative moderne, ultra-rapide et autonome à PowerPoint et Impress. Sans serveur requis, vos présentations fonctionnent partout, même hors-ligne.',
          x: 100,
          y: 320,
          width: 680,
          height: 70,
          rotation: 0,
          opacity: 0.85,
          zIndex: 6,
          fontSize: 18,
          fontWeight: '400',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#cbd5e1',
          textAlign: 'left',
          lineHeight: 1.5,
          animation: {
            type: 'fade-in',
            trigger: 'after-previous',
            duration: 0.6,
            delay: 0.2,
            order: 4,
          },
        },
        {
          id: 'el-hero-card-1',
          type: 'shape',
          name: 'Boîte Stat 1',
          shapeType: 'rounded-rect',
          x: 100,
          y: 430,
          width: 220,
          height: 80,
          rotation: 0,
          opacity: 0.95,
          zIndex: 7,
          fillColor: 'rgba(30, 41, 59, 0.7)',
          strokeColor: 'rgba(255, 255, 255, 0.12)',
          strokeWidth: 1,
          borderRadius: 14,
          animation: {
            type: 'slide-up',
            trigger: 'after-previous',
            duration: 0.5,
            delay: 0.1,
            order: 5,
          },
        },
        {
          id: 'el-hero-text-1',
          type: 'text',
          name: 'Texte Stat 1',
          content: '⚡ 100% Navigateur\nZéro installation requise',
          x: 116,
          y: 445,
          width: 190,
          height: 50,
          rotation: 0,
          opacity: 1,
          zIndex: 8,
          fontSize: 14,
          fontWeight: '600',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#f8fafc',
          textAlign: 'left',
          lineHeight: 1.4,
        },
        {
          id: 'el-hero-card-2',
          type: 'shape',
          name: 'Boîte Stat 2',
          shapeType: 'rounded-rect',
          x: 340,
          y: 430,
          width: 220,
          height: 80,
          rotation: 0,
          opacity: 0.95,
          zIndex: 9,
          fillColor: 'rgba(30, 41, 59, 0.7)',
          strokeColor: 'rgba(255, 255, 255, 0.12)',
          strokeWidth: 1,
          borderRadius: 14,
          animation: {
            type: 'slide-up',
            trigger: 'with-previous',
            duration: 0.5,
            delay: 0,
            order: 5,
          },
        },
        {
          id: 'el-hero-text-2',
          type: 'text',
          name: 'Texte Stat 2',
          content: '📦 Export Autonome\nFichier .HTML & .hmdslides',
          x: 356,
          y: 445,
          width: 190,
          height: 50,
          rotation: 0,
          opacity: 1,
          zIndex: 10,
          fontSize: 14,
          fontWeight: '600',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#f8fafc',
          textAlign: 'left',
          lineHeight: 1.4,
        },
        {
          id: 'el-hero-card-3',
          type: 'shape',
          name: 'Boîte Stat 3',
          shapeType: 'rounded-rect',
          x: 580,
          y: 430,
          width: 220,
          height: 80,
          rotation: 0,
          opacity: 0.95,
          zIndex: 11,
          fillColor: 'rgba(30, 41, 59, 0.7)',
          strokeColor: 'rgba(255, 255, 255, 0.12)',
          strokeWidth: 1,
          borderRadius: 14,
          animation: {
            type: 'slide-up',
            trigger: 'with-previous',
            duration: 0.5,
            delay: 0,
            order: 5,
          },
        },
        {
          id: 'el-hero-text-3',
          type: 'text',
          name: 'Texte Stat 3',
          content: '🔒 Données Privées\nStockage localisé garanti',
          x: 596,
          y: 445,
          width: 190,
          height: 50,
          rotation: 0,
          opacity: 1,
          zIndex: 12,
          fontSize: 14,
          fontWeight: '600',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#f8fafc',
          textAlign: 'left',
          lineHeight: 1.4,
        },
      ],
    },

    // Diapositive 2 : Fonctionnalités Clés
    {
      id: 'slide-2',
      title: 'Fonctionnalités Clés & Richesse',
      layout: 'two-column',
      notes:
        'Mettre l’accent sur la polyvalence des outils : texte riche, formes géométriques, alignements intelligents et gestion des calques.',
      transition: { type: 'slide', duration: 0.5 },
      background: {
        type: 'solid',
        color: '#0f172a',
      },
      elements: [
        {
          id: 's2-title',
          type: 'text',
          name: 'Titre Diapo 2',
          content: 'Un Atelier Complet de Création Visuelle',
          x: 80,
          y: 60,
          width: 800,
          height: 50,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          fontSize: 34,
          fontWeight: '800',
          fontFamily: 'Cabinet Grotesk, sans-serif',
          color: '#ffffff',
          textAlign: 'left',
        },
        {
          id: 's2-subtitle',
          type: 'text',
          name: 'Sous-titre Diapo 2',
          content: 'Tous les outils professionnels indispensables réunis dans une interface épurée.',
          x: 80,
          y: 115,
          width: 700,
          height: 30,
          rotation: 0,
          opacity: 0.8,
          zIndex: 2,
          fontSize: 16,
          fontWeight: '400',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#94a3b8',
          textAlign: 'left',
        },
        // Colonne 1
        {
          id: 's2-card-1',
          type: 'shape',
          name: 'Carte Outils',
          shapeType: 'rounded-rect',
          x: 80,
          y: 170,
          width: 400,
          height: 330,
          rotation: 0,
          opacity: 0.9,
          zIndex: 3,
          fillColor: 'rgba(30, 41, 59, 0.65)',
          strokeColor: 'rgba(255, 255, 255, 0.1)',
          strokeWidth: 1,
          borderRadius: 16,
        },
        {
          id: 's2-c1-title',
          type: 'text',
          name: 'Titre Carte 1',
          content: '🎨 Objets & Manipulation Directe',
          x: 105,
          y: 195,
          width: 350,
          height: 35,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          fontSize: 18,
          fontWeight: '700',
          fontFamily: 'Cabinet Grotesk, sans-serif',
          color: '#38bdf8',
        },
        {
          id: 's2-c1-desc',
          type: 'text',
          name: 'Points Clés 1',
          content:
            '• Textes stylisés avec polices web, interligne, ombres\n• 15+ Formes géométriques vectorielles redimensionnables\n• Images avec filtres, arrondis et rotation libre\n• Sélection multiple, groupage et verrouillage\n• Guides magnétiques d’alignement automatique',
          x: 105,
          y: 240,
          width: 350,
          height: 230,
          rotation: 0,
          opacity: 0.9,
          zIndex: 5,
          fontSize: 14,
          fontWeight: '400',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#cbd5e1',
          lineHeight: 1.8,
        },
        // Colonne 2
        {
          id: 's2-card-2',
          type: 'shape',
          name: 'Carte Animations',
          shapeType: 'rounded-rect',
          x: 520,
          y: 170,
          width: 400,
          height: 330,
          rotation: 0,
          opacity: 0.9,
          zIndex: 6,
          fillColor: 'rgba(30, 41, 59, 0.65)',
          strokeColor: 'rgba(255, 255, 255, 0.1)',
          strokeWidth: 1,
          borderRadius: 16,
        },
        {
          id: 's2-c2-title',
          type: 'text',
          name: 'Titre Carte 2',
          content: '🎬 Animations & Scène de Présentation',
          x: 545,
          y: 195,
          width: 350,
          height: 35,
          rotation: 0,
          opacity: 1,
          zIndex: 7,
          fontSize: 18,
          fontWeight: '700',
          fontFamily: 'Cabinet Grotesk, sans-serif',
          color: '#a855f7',
        },
        {
          id: 's2-c2-desc',
          type: 'text',
          name: 'Points Clés 2',
          content:
            '• Timeline d’animation avec ordre et délais configurables\n• Transitions fluides entre diapositives (fondu, push, zoom)\n• Mode Présentation plein écran avec pointeur laser virtuel\n• Mode Présentateur avec chronomètre et notes secrètes\n• Outil Stylet interactif pour dessiner en direct en réunion',
          x: 545,
          y: 240,
          width: 350,
          height: 230,
          rotation: 0,
          opacity: 0.9,
          zIndex: 8,
          fontSize: 14,
          fontWeight: '400',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#cbd5e1',
          lineHeight: 1.8,
        },
      ],
    },

    // Diapositive 3 : Données, Graphiques & Tableaux
    {
      id: 'slide-3',
      title: 'Graphiques & Tableaux Interactifs',
      layout: 'comparison',
      notes:
        'Montrer que l’utilisateur peut éditer les données du graphique et les cellules du tableau à la volée directement depuis l’interface.',
      transition: { type: 'push', duration: 0.5 },
      background: {
        type: 'solid',
        color: '#0b1120',
      },
      elements: [
        {
          id: 's3-title',
          type: 'text',
          name: 'Titre Diapo 3',
          content: 'Performances Trimestrielles & Analyse',
          x: 80,
          y: 50,
          width: 750,
          height: 45,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          fontSize: 32,
          fontWeight: '800',
          fontFamily: 'Cabinet Grotesk, sans-serif',
          color: '#ffffff',
        },
        {
          id: 's3-chart',
          type: 'chart',
          name: 'Graphique Ventes',
          x: 80,
          y: 120,
          width: 440,
          height: 380,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          chartType: 'bar',
          chartTitle: 'Évolution du Chiffre d’Affaires (k€)',
          categories: ['T1', 'T2', 'T3', 'T4'],
          series: [
            { name: '2025', data: [120, 180, 240, 310], color: '#6366f1' },
            { name: '2026 (Obj)', data: [150, 220, 290, 420], color: '#06b6d4' },
          ],
          showLegend: true,
          showGrid: true,
          animation: {
            type: 'zoom-in',
            trigger: 'after-previous',
            duration: 0.6,
            delay: 0.1,
            order: 1,
          },
        },
        {
          id: 's3-table',
          type: 'table',
          name: 'Tableau Synthèse',
          x: 550,
          y: 140,
          width: 370,
          height: 250,
          rotation: 0,
          opacity: 1,
          zIndex: 3,
          tableRows: 4,
          tableCols: 3,
          headerRow: true,
          headerBg: '#4f46e5',
          altRowBg: 'rgba(30, 41, 59, 0.4)',
          cellBorderColor: 'rgba(255, 255, 255, 0.12)',
          cellPadding: 8,
          tableData: [
            ['Indicateur', 'Actuel', 'Cible'],
            ['Adoption', '84%', '95%'],
            ['Satisfaction', '4.9/5', '4.9/5'],
            ['Temps de prod.', '-45%', '-50%'],
          ],
          animation: {
            type: 'slide-left',
            trigger: 'after-previous',
            duration: 0.6,
            delay: 0.2,
            order: 2,
          },
        },
        {
          id: 's3-insight-box',
          type: 'shape',
          name: 'Cadre Constat',
          shapeType: 'rounded-rect',
          x: 550,
          y: 410,
          width: 370,
          height: 90,
          rotation: 0,
          opacity: 0.9,
          zIndex: 4,
          fillColor: 'rgba(16, 185, 129, 0.12)',
          strokeColor: '#10b981',
          strokeWidth: 1.5,
          borderRadius: 12,
        },
        {
          id: 's3-insight-text',
          type: 'text',
          name: 'Texte Constat',
          content:
            '💡 Constat clé : Une croissance accélérée de +35% grâce à l’efficacité des présentations autonomes.',
          x: 565,
          y: 425,
          width: 340,
          height: 60,
          rotation: 0,
          opacity: 1,
          zIndex: 5,
          fontSize: 13,
          fontWeight: '500',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#6ee7b7',
          lineHeight: 1.5,
        },
      ],
    },

    // Diapositive 4 : Diagramme & Flux de Processus
    {
      id: 'slide-4',
      title: 'Architecture & Diagramme de Flux',
      layout: 'section-header',
      notes:
        'Expliquer le cycle de vie d’un projet : de la conception visuelle jusqu’à l’export HTML autonome.',
      transition: { type: 'zoom', duration: 0.5 },
      background: {
        type: 'gradient',
        color: '#0f172a',
        gradient: {
          from: '#0f172a',
          to: '#172554',
          direction: 'to-b',
        },
      },
      elements: [
        {
          id: 's4-title',
          type: 'text',
          name: 'Titre Diapo 4',
          content: 'Cycle de Création Sans Friction',
          x: 80,
          y: 60,
          width: 800,
          height: 45,
          rotation: 0,
          opacity: 1,
          zIndex: 1,
          fontSize: 34,
          fontWeight: '800',
          fontFamily: 'Cabinet Grotesk, sans-serif',
          color: '#ffffff',
        },
        {
          id: 's4-subtitle',
          type: 'text',
          name: 'Sous-titre Diapo 4',
          content: 'Comment HMD Slides transforme vos idées en présentation interactive instantanée.',
          x: 80,
          y: 115,
          width: 700,
          height: 30,
          rotation: 0,
          opacity: 0.8,
          zIndex: 2,
          fontSize: 15,
          fontWeight: '400',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#94a3b8',
        },
        // Étape 1
        {
          id: 's4-step-1',
          type: 'shape',
          name: 'Étape 1 Boîte',
          shapeType: 'rounded-rect',
          x: 80,
          y: 200,
          width: 170,
          height: 180,
          rotation: 0,
          opacity: 0.95,
          zIndex: 3,
          fillColor: 'rgba(30, 41, 59, 0.8)',
          strokeColor: '#6366f1',
          strokeWidth: 2,
          borderRadius: 16,
        },
        {
          id: 's4-step1-icon',
          type: 'text',
          name: 'Icône Étape 1',
          content: '✍️\n01. Concevoir\n\nAjout de textes, formes, images et thèmes.',
          x: 95,
          y: 220,
          width: 140,
          height: 140,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          fontSize: 14,
          fontWeight: '600',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#ffffff',
          textAlign: 'center',
          lineHeight: 1.5,
        },
        // Flèche 1 -> 2
        {
          id: 's4-arrow-1',
          type: 'shape',
          name: 'Flèche 1',
          shapeType: 'arrow-right',
          x: 265,
          y: 275,
          width: 40,
          height: 30,
          rotation: 0,
          opacity: 0.8,
          zIndex: 5,
          fillColor: '#818cf8',
        },
        // Étape 2
        {
          id: 's4-step-2',
          type: 'shape',
          name: 'Étape 2 Boîte',
          shapeType: 'rounded-rect',
          x: 320,
          y: 200,
          width: 170,
          height: 180,
          rotation: 0,
          opacity: 0.95,
          zIndex: 6,
          fillColor: 'rgba(30, 41, 59, 0.8)',
          strokeColor: '#06b6d4',
          strokeWidth: 2,
          borderRadius: 16,
        },
        {
          id: 's4-step2-icon',
          type: 'text',
          name: 'Icône Étape 2',
          content: '🎬\n02. Animer\n\nTransitions douces et effets séquentiels.',
          x: 335,
          y: 220,
          width: 140,
          height: 140,
          rotation: 0,
          opacity: 1,
          zIndex: 7,
          fontSize: 14,
          fontWeight: '600',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#ffffff',
          textAlign: 'center',
          lineHeight: 1.5,
        },
        // Flèche 2 -> 3
        {
          id: 's4-arrow-2',
          type: 'shape',
          name: 'Flèche 2',
          shapeType: 'arrow-right',
          x: 505,
          y: 275,
          width: 40,
          height: 30,
          rotation: 0,
          opacity: 0.8,
          zIndex: 8,
          fillColor: '#22d3ee',
        },
        // Étape 3
        {
          id: 's4-step-3',
          type: 'shape',
          name: 'Étape 3 Boîte',
          shapeType: 'rounded-rect',
          x: 560,
          y: 200,
          width: 170,
          height: 180,
          rotation: 0,
          opacity: 0.95,
          zIndex: 9,
          fillColor: 'rgba(30, 41, 59, 0.8)',
          strokeColor: '#10b981',
          strokeWidth: 2,
          borderRadius: 16,
        },
        {
          id: 's4-step3-icon',
          type: 'text',
          name: 'Icône Étape 3',
          content: '🎤\n03. Présenter\n\nPlein écran, pointeur laser et chronomètre.',
          x: 575,
          y: 220,
          width: 140,
          height: 140,
          rotation: 0,
          opacity: 1,
          zIndex: 10,
          fontSize: 14,
          fontWeight: '600',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#ffffff',
          textAlign: 'center',
          lineHeight: 1.5,
        },
        // Flèche 3 -> 4
        {
          id: 's4-arrow-3',
          type: 'shape',
          name: 'Flèche 3',
          shapeType: 'arrow-right',
          x: 745,
          y: 275,
          width: 40,
          height: 30,
          rotation: 0,
          opacity: 0.8,
          zIndex: 11,
          fillColor: '#34d399',
        },
        // Étape 4
        {
          id: 's4-step-4',
          type: 'shape',
          name: 'Étape 4 Boîte',
          shapeType: 'rounded-rect',
          x: 800,
          y: 200,
          width: 170,
          height: 180,
          rotation: 0,
          opacity: 0.95,
          zIndex: 12,
          fillColor: 'rgba(30, 41, 59, 0.8)',
          strokeColor: '#f59e0b',
          strokeWidth: 2,
          borderRadius: 16,
        },
        {
          id: 's4-step4-icon',
          type: 'text',
          name: 'Icône Étape 4',
          content: '🚀\n04. Diffuser\n\nExport HTML autonome & .hmdslides.',
          x: 815,
          y: 220,
          width: 140,
          height: 140,
          rotation: 0,
          opacity: 1,
          zIndex: 13,
          fontSize: 14,
          fontWeight: '600',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#ffffff',
          textAlign: 'center',
          lineHeight: 1.5,
        },
      ],
    },

    // Diapositive 5 : Synthèse & Conclusion
    {
      id: 'slide-5',
      title: 'Synthèse & Conclusion',
      layout: 'quote',
      notes:
        'Conclure la présentation. Inviter les spectateurs à tester l’export HTML pour constater son autonomie complète.',
      transition: { type: 'fade', duration: 0.6 },
      background: {
        type: 'gradient',
        color: '#0f172a',
        gradient: {
          from: '#1e1b4b',
          to: '#0f172a',
          direction: 'to-t',
        },
      },
      elements: [
        {
          id: 's5-quote-mark',
          type: 'text',
          name: 'Guillemet',
          content: '“',
          x: 100,
          y: 100,
          width: 80,
          height: 80,
          rotation: 0,
          opacity: 0.35,
          zIndex: 1,
          fontSize: 96,
          fontWeight: '700',
          fontFamily: 'Playfair Display, serif',
          color: '#818cf8',
        },
        {
          id: 's5-quote-text',
          type: 'text',
          name: 'Citation',
          content:
            'La simplicité est la sophistication suprême.\nHMD Slides redonne le contrôle créatif sans compromis de performance.',
          x: 140,
          y: 160,
          width: 740,
          height: 120,
          rotation: 0,
          opacity: 1,
          zIndex: 2,
          fontSize: 28,
          fontWeight: '600',
          fontFamily: 'Cabinet Grotesk, sans-serif',
          color: '#f8fafc',
          textAlign: 'left',
          lineHeight: 1.4,
        },
        {
          id: 's5-author',
          type: 'text',
          name: 'Auteur',
          content: '— Conçu avec passion pour des présentations fluides & mémorables.',
          x: 140,
          y: 300,
          width: 600,
          height: 30,
          rotation: 0,
          opacity: 0.8,
          zIndex: 3,
          fontSize: 16,
          fontWeight: '500',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#94a3b8',
        },
        {
          id: 's5-cta-btn',
          type: 'shape',
          name: 'Bouton Fin',
          shapeType: 'rounded-rect',
          x: 140,
          y: 380,
          width: 260,
          height: 54,
          rotation: 0,
          opacity: 1,
          zIndex: 4,
          fillColor: '#4f46e5',
          strokeColor: '#818cf8',
          strokeWidth: 1.5,
          borderRadius: 27,
          animation: {
            type: 'bounce-in',
            trigger: 'after-previous',
            duration: 0.6,
            delay: 0.2,
            order: 1,
          },
        },
        {
          id: 's5-cta-text',
          type: 'text',
          name: 'Texte Bouton',
          content: '🚀 Lancez votre Présentation',
          x: 155,
          y: 395,
          width: 230,
          height: 25,
          rotation: 0,
          opacity: 1,
          zIndex: 5,
          fontSize: 15,
          fontWeight: '700',
          fontFamily: 'Plus Jakarta Sans, sans-serif',
          color: '#ffffff',
          textAlign: 'center',
        },
      ],
    },
  ],
};
