import { PresentationTheme } from '../types/slides';

export const PRESENTATION_THEMES: PresentationTheme[] = [
  {
    id: 'moderne',
    name: 'Moderne (Glass & Indigo)',
    primaryColor: '#6366f1',
    secondaryColor: '#8b5cf6',
    accentColor: '#06b6d4',
    bgColor: '#0f172a',
    bgGradient: {
      from: '#0f172a',
      to: '#1e1b4b',
      direction: 'to-br',
    },
    textColor: '#f8fafc',
    mutedTextColor: '#94a3b8',
    titleFont: 'Cabinet Grotesk, sans-serif',
    bodyFont: 'Plus Jakarta Sans, sans-serif',
    cardBg: 'rgba(30, 41, 59, 0.7)',
    cardBorder: 'rgba(255, 255, 255, 0.1)',
    isDark: true,
  },
  {
    id: 'minimal',
    name: 'Minimaliste (Noir & Blanc)',
    primaryColor: '#0f172a',
    secondaryColor: '#334155',
    accentColor: '#2563eb',
    bgColor: '#ffffff',
    bgGradient: {
      from: '#ffffff',
      to: '#f8fafc',
      direction: 'to-b',
    },
    textColor: '#0f172a',
    mutedTextColor: '#64748b',
    titleFont: 'Inter, sans-serif',
    bodyFont: 'Inter, sans-serif',
    cardBg: '#ffffff',
    cardBorder: '#e2e8f0',
    isDark: false,
  },
  {
    id: 'sombre',
    name: 'Sombre Tech (Carbone & Émeraude)',
    primaryColor: '#10b981',
    secondaryColor: '#065f46',
    accentColor: '#34d399',
    bgColor: '#090d16',
    bgGradient: {
      from: '#090d16',
      to: '#0f172a',
      direction: 'to-b',
    },
    textColor: '#f1f5f9',
    mutedTextColor: '#64748b',
    titleFont: 'JetBrains Mono, monospace',
    bodyFont: 'Plus Jakarta Sans, sans-serif',
    cardBg: 'rgba(15, 23, 42, 0.85)',
    cardBorder: 'rgba(16, 185, 129, 0.2)',
    isDark: true,
  },
  {
    id: 'professionnel',
    name: 'Professionnel (Bleu Marine & Platine)',
    primaryColor: '#1e3a8a',
    secondaryColor: '#3b82f6',
    accentColor: '#f59e0b',
    bgColor: '#f8fafc',
    bgGradient: {
      from: '#f8fafc',
      to: '#e2e8f0',
      direction: 'to-b',
    },
    textColor: '#0f172a',
    mutedTextColor: '#475569',
    titleFont: 'Montserrat, sans-serif',
    bodyFont: 'Plus Jakarta Sans, sans-serif',
    cardBg: '#ffffff',
    cardBorder: '#cbd5e1',
    isDark: false,
  },
  {
    id: 'education',
    name: 'Éducation (Saphir & Ambre)',
    primaryColor: '#0284c7',
    secondaryColor: '#d97706',
    accentColor: '#10b981',
    bgColor: '#fdfbf7',
    bgGradient: {
      from: '#fdfbf7',
      to: '#f3ede2',
      direction: 'to-br',
    },
    textColor: '#1c1917',
    mutedTextColor: '#57534e',
    titleFont: 'Merriweather, serif',
    bodyFont: 'Plus Jakarta Sans, sans-serif',
    cardBg: '#ffffff',
    cardBorder: '#e7e5e4',
    isDark: false,
  },
  {
    id: 'colore',
    name: 'Créatif & Coloré (Corail & Turquoise)',
    primaryColor: '#f43f5e',
    secondaryColor: '#0d9488',
    accentColor: '#fbbf24',
    bgColor: '#fff1f2',
    bgGradient: {
      from: '#fff1f2',
      to: '#f0fdfa',
      direction: 'to-tr',
    },
    textColor: '#1e293b',
    mutedTextColor: '#64748b',
    titleFont: 'Syne, sans-serif',
    bodyFont: 'Plus Jakarta Sans, sans-serif',
    cardBg: '#ffffff',
    cardBorder: '#fecdd3',
    isDark: false,
  },
  {
    id: 'glass',
    name: 'Glassmorphism Liquide',
    primaryColor: '#a855f7',
    secondaryColor: '#ec4899',
    accentColor: '#38bdf8',
    bgColor: '#18182b',
    bgGradient: {
      from: '#13111c',
      to: '#231b39',
      direction: 'to-br',
    },
    textColor: '#ffffff',
    mutedTextColor: '#cbd5e1',
    titleFont: 'Cabinet Grotesk, sans-serif',
    bodyFont: 'Plus Jakarta Sans, sans-serif',
    cardBg: 'rgba(255, 255, 255, 0.08)',
    cardBorder: 'rgba(255, 255, 255, 0.18)',
    isDark: true,
  },
  {
    id: 'gradient',
    name: 'Gradient Crépuscule (Sunset Aura)',
    primaryColor: '#f97316',
    secondaryColor: '#db2777',
    accentColor: '#fbbf24',
    bgColor: '#180e29',
    bgGradient: {
      from: '#1e1136',
      to: '#381232',
      direction: 'to-r',
    },
    textColor: '#fdf4ff',
    mutedTextColor: '#d8b4fe',
    titleFont: 'Playfair Display, serif',
    bodyFont: 'Plus Jakarta Sans, sans-serif',
    cardBg: 'rgba(49, 18, 59, 0.6)',
    cardBorder: 'rgba(244, 114, 182, 0.25)',
    isDark: true,
  },
];

export function getThemeById(themeId: string, customTheme?: PresentationTheme): PresentationTheme {
  if (customTheme && customTheme.id === themeId) {
    return customTheme;
  }
  return PRESENTATION_THEMES.find((t) => t.id === themeId) || PRESENTATION_THEMES[0];
}
